<h1> Day 01

In [1]:
#Importing Tensorflow
% tensorflow_version 2.x
import tensorflow as tf
tf.__version__


'2.8.2'

In [5]:
#Create tensors using tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [9]:
matrix = tf.constant([[1,1,1,1],
                      [2,2,2,2]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int32)>

In [10]:
matrix.ndim

2

In [15]:
tensor = tf.constant([[[1,1,1,1],
                       [2,2,2,2]],
                      [ [3,3,3,3],
                       [4,4,4,4]]], dtype=tf.float16)
tensor

<tf.Tensor: shape=(2, 2, 4), dtype=float16, numpy=
array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [4., 4., 4., 4.]]], dtype=float16)>

### Creating tensor using tf.variable() function

In [16]:
ch_tensor = tf.Variable([1,7])
ch_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [17]:
# this one is a changable tensor but tf.constant() tensor are not changable

ch_tensor[0].assign(7)
ch_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensor using tensorflow

In [25]:
# creating random tensor with same value

random_1 = tf.random.Generator.from_seed(23)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(23)
random_2 = random_2.normal(shape=(3,2))
random_2

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892],
        [-1.5700307 ,  0.4457582 ],
        [ 0.10944034, -0.8035768 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892],
        [-1.5700307 ,  0.4457582 ],
        [ 0.10944034, -0.8035768 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffling the order of the tensor

In [52]:
unshuffled = tf.constant([[1,1,1,1],
                          [2,2,2,2],
                          [3,3,3,3]], dtype=tf.float16)
unshuffled

shuffled = tf.random.shuffle(unshuffled)

#we can get same shuffle data by adding seed= x
tf.random.set_seed(24)
shuffled1 = tf.random.shuffle(unshuffled, seed=24)
shuffled1, shuffled

(<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
 array([[3., 3., 3., 3.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]], dtype=float16)>,
 <tf.Tensor: shape=(3, 4), dtype=float16, numpy=
 array([[2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.]], dtype=float16)>)

## indexing tensor

In [61]:
rank_2_tensor = tf.constant([[1,1,1],
                             [2,2,2]])
rank_2_tensor[:1]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 1, 1]], dtype=int32)>

In [63]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [1],
        [1]],

       [[2],
        [2],
        [2]]], dtype=int32)>

In [64]:
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 meand expand last one(final axis)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [1],
        [1]],

       [[2],
        [2],
        [2]]], dtype=int32)>

In [65]:
tf.expand_dims(rank_2_tensor, axis=1)   # 1 means expand at middle

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 1, 1]],

       [[2, 2, 2]]], dtype=int32)>

In [66]:
tf.expand_dims(rank_2_tensor, axis=0)  # 0 means expand at first axis

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2]]], dtype=int32)>

##Manupulating Tensor

In [67]:
t1 = tf.constant([1,2,3,4])
t1 +10

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [68]:
t1 - 10

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-9, -8, -7, -6], dtype=int32)>

In [69]:
t1  #t1 will never change bcz it's constant

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [79]:
t2 = tf.constant([[1,1],
                  [2,2]])

In [80]:
#dot product 

tf.tensordot(t2,t2, axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [6, 6]], dtype=int32)>

In [85]:
## matrix multiplication

x = tf.constant([[1,1,1],
                 [2,2,2]])

y = tf.constant([[3,3,3],
                 [4,4,4]])

tf.matmul(x,tf.transpose(y))  , tf.matmul(tf.transpose(x),y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 9, 12],
        [18, 24]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]], dtype=int32)>)

In [86]:
t1.dtype

tf.int32

In [89]:
#changing data_type
t2= tf.cast(t1,tf.float32)
t2.dtype

tf.float32